server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp

dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-jt-web  #服务名称"唯一"
  registry:
    address: zookeeper://192.168.175.129:2181?backup=192.168.175.129:2182,192.168.175.129:2183


  